<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <IsPackable>false</IsPackable>
    <VersionPrefix>0.1.0</VersionPrefix>
    <VersionSuffix>alpha</VersionSuffix>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Twinbox contributors</Authors>
    <Copyright>Copyright (c) Twinbox contributors</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/twinbox-dotnet/twinbox</PackageProjectUrl>
    <RepositoryUrl>https://github.com/twinbox-dotnet/twinbox</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>outbox;inbox;transactional-outbox;messaging;idempotency;efcore;azure-service-bus;azure-functions;rabbitmq;kafka;nats;jetstream;redis;amazon-sqs;amazon-sns;pulsar</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
