using System.Collections.Generic;
using System.Text;

namespace Twinbox.SourceGenerators;

internal static class RegistrationEmitter
{
    /// <summary>PascalCases the assembly name into an identifier suffix: "My.App-Api" becomes "MyAppApi".</summary>
    public static string ToIdentifier(string? assemblyName)
    {
        var result = new StringBuilder();
        var upperNext = true;
        foreach (var c in assemblyName ?? string.Empty)
        {
            if (!char.IsLetterOrDigit(c))
            {
                upperNext = true;
                continue;
            }

            result.Append(upperNext ? char.ToUpperInvariant(c) : c);
            upperNext = false;
        }

        return result.Length == 0 ? "Assembly" : result.ToString();
    }

    public static string Emit(string assemblyIdentifier, IReadOnlyList<(string Handler, string Message)> registrations)
    {
        var source = new StringBuilder()
            .Append("// <auto-generated/>\n")
            .Append("#nullable enable\n")
            .Append('\n')
            .Append("namespace Twinbox\n")
            .Append("{\n")
            .Append("    [global::System.CodeDom.Compiler.GeneratedCode(\"Twinbox.SourceGenerators\", \"1.0.0\")]\n")
            .Append("    internal static class ").Append(assemblyIdentifier).Append("HandlerRegistrations\n")
            .Append("    {\n")
            .Append("        /// <summary>Registers every <see cref=\"global::Twinbox.IHandle{TMessage}\"/> in this assembly without reflection: <c>services.AddTwinbox(b => b.AddHandlersFrom")
            .Append(assemblyIdentifier).Append("())</c>.\n")
            .Append("        /// Generic and abstract handlers are skipped (TWBX001) and need AddHandler&lt;THandler, TMessage&gt;().</summary>\n")
            .Append("        public static global::Twinbox.TwinboxBuilder AddHandlersFrom").Append(assemblyIdentifier)
            .Append("(this global::Twinbox.TwinboxBuilder builder)\n")
            .Append("        {\n");

        foreach (var (handler, message) in registrations)
        {
            source.Append("            builder.AddHandler<").Append(handler).Append(", ").Append(message).Append(">();\n");
        }

        return source
            .Append("            return builder;\n")
            .Append("        }\n")
            .Append("    }\n")
            .Append("}\n")
            .ToString();
    }
}
