<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Testcontainers.Pulsar" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Twinbox.Pulsar/Twinbox.Pulsar.csproj" />
  </ItemGroup>
</Project>
