<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Transactional outbox and inbox for .NET: reliable delivery to any message broker with built-in deduplication.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Twinbox.Abstractions/Twinbox.Abstractions.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
