using System.Globalization;
using System.Text;

namespace Twinbox.Relational;

/// <summary>Column types match what Oracle's EF Core provider generates for AddTwinbox(), so both stores share tables.</summary>
internal sealed partial class RelationalDialect
{
    /// <summary>Oracle has no multi-row VALUES before 23ai, so rows go in as one anonymous block.</summary>
    private string OracleInsert(int rows)
    {
        var columns = string.Join(", ", OutboxColumns.Select(Quote));
        var sql = new StringBuilder("BEGIN\n");
        for (var row = 0; row < rows; row++)
        {
            sql.Append(CultureInfo.InvariantCulture, $"INSERT INTO {Outbox} ({columns}) VALUES (")
                .Append(string.Join(", ", OutboxColumns.Select(c => $":{c}{row}")))
                .Append(");\n");
        }

        return sql.Append("END;").ToString();
    }

    /// <summary>A schema is an Oracle user, which takes DBA rights to create, so it must already exist.</summary>
    private string OracleSchema()
    {
        var outbox = _settings.OutboxTable;
        var inbox = _settings.InboxTable;
        (string Name, string Sql)[] statements =
        [
            (outbox, $"""
            CREATE TABLE {Outbox} (
                "Sequence" NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                "Id" RAW(16) NOT NULL,
                "MessageName" NVARCHAR2(256) NOT NULL,
                "Transport" NVARCHAR2(64) NOT NULL,
                "Destination" NVARCHAR2(256) NOT NULL,
                "PartitionKey" NVARCHAR2(256) NULL,
                "TenantId" NVARCHAR2(128) NULL,
                "Payload" BLOB NOT NULL,
                "ContentType" NVARCHAR2(128) NOT NULL,
                "Headers" NCLOB NOT NULL,
                "TraceParent" NVARCHAR2(64) NULL,
                "CreatedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                "AvailableAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                "Attempts" NUMBER(10) NOT NULL,
                "Status" NUMBER(10) NOT NULL,
                "LeaseOwner" NVARCHAR2(256) NULL,
                "LeaseUntil" TIMESTAMP(6) WITH TIME ZONE NULL,
                "LastError" NVARCHAR2(2000) NULL,
                "SentAt" TIMESTAMP(6) WITH TIME ZONE NULL,
                CONSTRAINT {Quote($"PK_{outbox}")} PRIMARY KEY ("Sequence"))
            """),
            ($"IX_{outbox}_Id", $"""CREATE UNIQUE INDEX {Index($"IX_{outbox}_Id")} ON {Outbox} ("Id")"""),
            ($"IX_{outbox}_Status_AvailableAt", $"""CREATE INDEX {Index($"IX_{outbox}_Status_AvailableAt")} ON {Outbox} ("Status", "AvailableAt")"""),
            ($"IX_{outbox}_PartitionKey_Status", $"""CREATE INDEX {Index($"IX_{outbox}_PartitionKey_Status")} ON {Outbox} ("PartitionKey", "Status")"""),
            (inbox, $"""
            CREATE TABLE {Inbox} (
                "MessageId" NVARCHAR2(256) NOT NULL,
                "Consumer" NVARCHAR2(256) NOT NULL,
                "Source" NVARCHAR2(256) NOT NULL,
                "ProcessedAt" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                CONSTRAINT {Quote($"PK_{inbox}")} PRIMARY KEY ("MessageId", "Consumer"))
            """),
            ($"IX_{inbox}_ProcessedAt", $"""CREATE INDEX {Index($"IX_{inbox}_ProcessedAt")} ON {Inbox} ("ProcessedAt")"""),
        ];

        var owner = _settings.Schema is null ? "USER" : Literal(_settings.Schema);
        var calls = string.Join('\n', statements.Select(s => $"    run({Literal(s.Name)}, {Literal(s.Sql)});"));

        // DDL on a busy table fails on its lock before checking the name, so existing objects are skipped up front and
        // the lock timeout covers a concurrent creator; -955/-1408 then mean the other instance won.
        return $"""
            DECLARE
                PROCEDURE run(name VARCHAR2, statement VARCHAR2) IS
                    existing NUMBER;
                BEGIN
                    SELECT COUNT(*) INTO existing FROM all_objects WHERE owner = {owner} AND object_name = name;
                    IF existing = 0 THEN
                        EXECUTE IMMEDIATE statement;
                    END IF;
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
                END;
            BEGIN
                EXECUTE IMMEDIATE 'ALTER SESSION SET DDL_LOCK_TIMEOUT = 30';
            {calls}
            END;
            """;
    }

    private static string Literal(string value) => $"'{value.Replace("'", "''", StringComparison.Ordinal)}'";

    private string Index(string name) => _settings.Schema is null ? Quote(name) : $"{Quote(_settings.Schema)}.{Quote(name)}";
}
