using System.Globalization;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Twinbox.SourceGenerators.Tests;

public sealed class HandlerRegistrationGeneratorTests
{
    private const string Messages = """
        using System.Threading;
        using System.Threading.Tasks;

        namespace MyApp;

        public sealed record OrderPlaced(int OrderId);
        public sealed record OrderShipped(int OrderId);

        """;

    [Fact]
    public void MultipleHandlers_AreRegisteredInDeterministicOrder()
    {
        var result = GeneratorHarness.Run(Messages + $$"""
            public sealed class ZebraHandler : Twinbox.IHandle<OrderPlaced>
            {
                {{Handle("OrderPlaced")}}
            }

            public sealed class AlphaHandler : Twinbox.IHandle<OrderShipped>
            {
                {{Handle("OrderShipped")}}
            }
            """);

        const string expected = """
            // <auto-generated/>
            #nullable enable

            namespace Twinbox
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Twinbox.SourceGenerators", "1.0.0")]
                internal static class MyAppHandlerRegistrations
                {
            {{DOC}}
                    public static global::Twinbox.TwinboxBuilder AddHandlersFromMyApp(this global::Twinbox.TwinboxBuilder builder)
                    {
                        builder.AddHandler<global::MyApp.AlphaHandler, global::MyApp.OrderShipped>();
                        builder.AddHandler<global::MyApp.ZebraHandler, global::MyApp.OrderPlaced>();
                        return builder;
                    }
                }
            }

            """;
        var doc = string.Concat(
            "        /// <summary>Registers every <see cref=\"global::Twinbox.IHandle{TMessage}\"/> in this assembly without reflection: ",
            "<c>services.AddTwinbox(b => b.AddHandlersFromMyApp())</c>.\n",
            "        /// Generic and abstract handlers are skipped (TWBX001) and need AddHandler&lt;THandler, TMessage&gt;().</summary>");
        Assert.Equal(expected.ReplaceLineEndings("\n").Replace("{{DOC}}", doc, StringComparison.Ordinal), result.Source);
    }

    [Fact]
    public void HandlerOfTwoMessages_RegistersEachPair()
    {
        var result = GeneratorHarness.Run(Messages + $$"""
            public sealed class OrderHandler : Twinbox.IHandle<OrderShipped>, Twinbox.IHandle<OrderPlaced>
            {
                {{Handle("OrderPlaced")}}
                {{Handle("OrderShipped")}}
            }
            """);

        Assert.Equal(
            [
                "builder.AddHandler<global::MyApp.OrderHandler, global::MyApp.OrderPlaced>();",
                "builder.AddHandler<global::MyApp.OrderHandler, global::MyApp.OrderShipped>();",
            ],
            Registrations(result));
    }

    [Fact]
    public void BatchHandler_IsRegisteredWithAddBatchHandler()
    {
        var result = GeneratorHarness.Run(Messages + """
            public sealed class ImportHandler : Twinbox.IHandleBatch<OrderPlaced>
            {
                public Task HandleAsync(System.Collections.Generic.IReadOnlyList<Twinbox.BatchItem<OrderPlaced>> batch, CancellationToken cancellationToken) => Task.CompletedTask;
            }
            """);

        Assert.Equal(["builder.AddBatchHandler<global::MyApp.ImportHandler, global::MyApp.OrderPlaced>();"], Registrations(result));
    }

    [Fact]
    public void NestedPublicHandler_IsRegistered()
    {
        var result = GeneratorHarness.Run(Messages + $$"""
            public static class Features
            {
                public sealed class NestedHandler : Twinbox.IHandle<OrderPlaced>
                {
                    {{Handle("OrderPlaced")}}
                }
            }
            """);

        Assert.Equal(["builder.AddHandler<global::MyApp.Features.NestedHandler, global::MyApp.OrderPlaced>();"], Registrations(result));
    }

    [Fact]
    public void InternalHandler_IsRegistered()
    {
        var result = GeneratorHarness.Run(Messages + $$"""
            internal sealed class InternalHandler : Twinbox.IHandle<OrderPlaced>
            {
                {{Handle("OrderPlaced")}}
            }
            """);

        Assert.Equal(["builder.AddHandler<global::MyApp.InternalHandler, global::MyApp.OrderPlaced>();"], Registrations(result));
    }

    [Fact]
    public void PrivateNestedHandler_IsSkipped()
    {
        var result = GeneratorHarness.Run(Messages + $$"""
            public sealed class Outer
            {
                private sealed class HiddenHandler : Twinbox.IHandle<OrderPlaced>
                {
                    {{Handle("OrderPlaced")}}
                }

                public sealed class VisibleHandler : Twinbox.IHandle<OrderShipped>
                {
                    {{Handle("OrderShipped")}}
                }
            }
            """);

        Assert.Equal(["builder.AddHandler<global::MyApp.Outer.VisibleHandler, global::MyApp.OrderShipped>();"], Registrations(result));
        Assert.DoesNotContain(result.Diagnostics, d => d.Id == "TWBX001");
    }

    [Fact]
    public void PartialHandler_IsRegisteredOnce()
    {
        var result = GeneratorHarness.Run(Messages + $$"""
            public sealed partial class SplitHandler : Twinbox.IHandle<OrderPlaced>
            {
                {{Handle("OrderPlaced")}}
            }

            public sealed partial class SplitHandler : System.IDisposable
            {
                public void Dispose() { }
            }
            """);

        Assert.Equal(["builder.AddHandler<global::MyApp.SplitHandler, global::MyApp.OrderPlaced>();"], Registrations(result));
    }

    [Fact]
    public void AbstractHandler_ReportsTwbx001AndConcreteSubclassIsRegistered()
    {
        var result = GeneratorHarness.Run(Messages + $$"""
            public abstract class BaseHandler : Twinbox.IHandle<OrderPlaced>
            {
                {{Handle("OrderPlaced")}}
            }

            public sealed class ConcreteHandler : BaseHandler;
            """);

        var diagnostic = Assert.Single(result.Diagnostics, d => d.Id == "TWBX001");
        Assert.Equal(DiagnosticSeverity.Info, diagnostic.Severity);
        Assert.Contains("'MyApp.BaseHandler' is abstract", diagnostic.GetMessage(CultureInfo.InvariantCulture), StringComparison.Ordinal);
        Assert.Equal("Handlers.cs", diagnostic.Location.GetLineSpan().Path);
        Assert.Equal("BaseHandler".Length, diagnostic.Location.SourceSpan.Length);
        Assert.Equal(["builder.AddHandler<global::MyApp.ConcreteHandler, global::MyApp.OrderPlaced>();"], Registrations(result));
    }

    [Fact]
    public void GenericHandler_ReportsTwbx001()
    {
        var result = GeneratorHarness.Run(Messages + """
            public sealed class AnyHandler<T> : Twinbox.IHandle<T>
                where T : class
            {
                public Task HandleAsync(T message, Twinbox.MessageContext context, CancellationToken cancellationToken) => Task.CompletedTask;
            }
            """);

        var diagnostic = Assert.Single(result.Diagnostics, d => d.Id == "TWBX001");
        Assert.Contains("is generic", diagnostic.GetMessage(CultureInfo.InvariantCulture), StringComparison.Ordinal);
        Assert.Empty(Registrations(result));
    }

    [Fact]
    public void GeneratedCode_CompilesWithoutErrorsOrWarnings()
    {
        var result = GeneratorHarness.Run(Messages + $$"""
            public sealed class OrderHandler : Twinbox.IHandle<OrderPlaced>, Twinbox.IHandle<OrderShipped>
            {
                {{Handle("OrderPlaced")}}
                {{Handle("OrderShipped")}}
            }

            internal sealed class AuditHandler : Twinbox.IHandle<OrderPlaced>
            {
                {{Handle("OrderPlaced")}}
            }

            public static class Startup
            {
                public static Twinbox.TwinboxBuilder Configure(Twinbox.TwinboxBuilder builder) =>
                    Twinbox.MyAppHandlerRegistrations.AddHandlersFromMyApp(builder);
            }
            """);

        Assert.Empty(result.Diagnostics);
        Assert.Empty(result.Output.GetDiagnostics().Where(d => d.Severity >= DiagnosticSeverity.Warning));
    }

    [Fact]
    public void CompilationWithoutTwinbox_GeneratesNothing()
    {
        var result = GeneratorHarness.Run("namespace MyApp; public sealed class Plain : System.IDisposable { public void Dispose() { } }", referenceTwinbox: false);

        Assert.Null(result.Source);
    }

    [Theory]
    [InlineData("MyApp", "MyApp")]
    [InlineData("Twinbox.UnitTests", "TwinboxUnitTests")]
    [InlineData("my-app.api", "MyAppApi")]
    [InlineData("...", "Assembly")]
    public void AssemblyName_IsSanitizedIntoMethodName(string assemblyName, string expected)
    {
        var result = GeneratorHarness.Run(Messages, assemblyName);

        Assert.Contains($"AddHandlersFrom{expected}(this", result.Source, StringComparison.Ordinal);
    }

    [Fact]
    public void UnrelatedEdit_KeepsPipelineCached()
    {
        var compilation = GeneratorHarness.CreateCompilation(Messages + $$"""
            public sealed class OrderHandler : Twinbox.IHandle<OrderPlaced>
            {
                {{Handle("OrderPlaced")}}
            }
            """);
        var driver = GeneratorHarness.CreateDriver().RunGenerators(compilation);

        var edited = compilation.AddSyntaxTrees(
            CSharpSyntaxTree.ParseText("namespace MyApp; public sealed class Unrelated;", GeneratorHarness.ParseOptions));
        var run = driver.RunGenerators(edited).GetRunResult().Results.Single();

        Assert.All(
            run.TrackedSteps[HandlerRegistrationGenerator.HandlersTrackingName].SelectMany(s => s.Outputs),
            o => Assert.True(o.Reason is IncrementalStepRunReason.Cached or IncrementalStepRunReason.Unchanged, o.Reason.ToString()));
        Assert.All(
            run.TrackedOutputSteps.SelectMany(s => s.Value).SelectMany(s => s.Outputs),
            o => Assert.Equal(IncrementalStepRunReason.Cached, o.Reason));
    }

    private static string Handle(string messageType) =>
        $"public Task HandleAsync({messageType} message, Twinbox.MessageContext context, CancellationToken cancellationToken) => Task.CompletedTask;";

    private static string[] Registrations(GeneratorResult result) =>
        [.. result.Source!.Split('\n').Select(l => l.Trim()).Where(l => l.StartsWith("builder.Add", StringComparison.Ordinal))];
}
